alkemyTech/OT130-CLIENT

package.json
src/App.js
src/Components/Auth/LoginForm.js
src/Components/Auth/loginForm.css

OT130-26-Form-Login

---

package.json
src/App.js
src/Components/Auth/RegisterForm.js
src/Components/FormStyles.css
src/Helpers/formValidations.js
src/Helpers/messagesText.js
src/Helpers/yupValidations.js
src/Services/privateApiService.js

**Resumen**
- Adaptación de código html  y funciones para el uso de formik
- Validación de todos los inputs del form
- Se crearon estilos para los mensajes de error y mensaje enviado en la hoja de estilos globales "FormsStyles.css".
**Evidencia**

Ot130 25 formulario registro parcial

---

src/Components/Auth/LoginForm.js
src/Components/Auth/loginForm.css

-Cambio de import de componentes de libreria en LoginForm.
- Corregido css en LoginForm.

OT130-173 Error en import de componentes Formulario Login

---

package.json
src/Components/Categories/CategoriesForm.js

En este PR se corrige la importación de las funciones exportadas desde categoriesService.js en el archivo CategoriesForm.js

Corrección de ruta Funciones CategoriesService

---

src/App.js
src/Components/Organization/OrganizationEditForm.js
src/Screens/Organization/OrganizationEdit.js
src/Services/organizationService.js

**Tarea**
-Formulario de actualización de datos de Organización
**Implementación**
-Uso de la librería CKEditor 
-Validaciones con yup de cada inputs
- Envió y actualización de datos utilizando el servicio

Ot130 34 formulario de actualizacion de datos de organizacion

---

src/Services/privateApiService.js

Cambié por error el get a post en el metodo Get. Este pr revierte ese cambio.

Fixed post on Get method

---

src/Components/Organization/OrganizationEditForm.js
src/Helpers/messagesText.js
src/Screens/Organization/OrganizationEdit.js
src/rutas/config.js

Se elimino imports de archivos css que aun no existen.
Se dio valor a una variable que no existia.

Ot 130 corrección de compilación en main

---

src/Components/Activities/ActivitiesContent.js
src/Components/Activities/ListHtml.js

[OT130-58](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT130/boards/197?modal=detail&selectedIssue=OT130-58)
**Tarea**
- Crear componente que  deberá permitir renderizar código HTML en lugar de texto plano

OT130-58-Crear-componente-contenido-de-actividad 

---

src/Components/Card/index.js
src/Components/Card/styles.css
src/Helpers/messagesText.js

Componente Card para utilizar en los listados de Novedades, Actividades, Últimas Novedades y Relacionadas.

OT130-60 Componente Card para mostrar en listados

---

src/Components/HomeForm/HomeForm.js
src/Components/WelcomeTextForm/WelcomeTextForm.js

Actualiza librería de alertas en componentes `WelcomeTextForm.js` y `HomeForm.js` de SweetAlert a SweetAlert2

Actualiza librería de alertas

---

src/.env.example
src/Services/contactsService.js
src/Services/privateApiService.js

[OT130-88](https://alkemy-labs.atlassian.net/jira/software/c/projects/OT130/boards/197?modal=detail&selectedIssue=OT130-88)
**Tarea** 
- Almacenar los endpoints de listado, creación, edición y eliminación de contactos en el archivo .env.
- Asegurarse que este archivo sea excluido en los commits.
- Agregar los placeholders de estas variables en el archivo .env.example, que SI debe ser commiteado.

Ot130 88 crear variables de entorno

---

.env.example
src/.env.example

**Tarea**
- Se movió a la ruta raíz  y se modificó.

Se movio el archivo .env.example a la carpeta raiz

---

README.md
src/Components/Skeleton/Skeleton.css
src/Components/Skeleton/Skeleton.js

Crea un componente Skeleton para mostrar un feedback al usuario cuando se esté realizando la carga de contenido y también documenta la implementación en README.md

Ot130 93 setup skeleton

---

src/Components/Activities/ActivitiesList.js

fixes #100. Borré el import del spinner de react-bootstrap que causaba el error

Fixed double import

---

src/Components/News/NewsForm.js
src/reducers/novedadesReducer.js

Eliminado el doble import innecesario en NewsForm
Agregado export default en novedadesReducer
fix #114

Fix errores de NewsForm y novedadesReducer

---

src/App.js
src/rutas/Backoffice.js
src/rutas/Public.js

-  Modificar el router existente para manejar la navegación del backoffice por separado de la navegación de la web pública

OT130-114 Modularizar router para disponer de ruteo público y admin

---

src/Components/Backoffice/Header.js
src/Components/Backoffice/Sidebar.js

**Qué**
- Creados componente Header que contiene el nombre de la ONG con un botón para desplegar el componente Sidebar.
- Creado componente Sidebar, dentro del cual se encuentra un Nav para completar con las rutas del backoffice.
**Para qué**
- Agregar la opción de navegar fácilmente por las rutas del backoffice
- Mejorar la interfaz de usuario para los administradores. 
**Evidencia**
https://user-images.githubusercontent.com/60374548/153935174-3891970f-5346-4eeb-bdd4-af05db62991a.mp4

OT130-123 Crear componente Header para backoffice

---

src/Components/Donations/DonationButton.js

Hola, se cambia la librería, ya que no está desplegando la información del botón de hamburguesa de donación y con el cambio de librería se resuelve el error.

Bug-fix Cambio de bootstrap a react-bootstrap en el componente Donations

---

src/routes/Public.js

Cambiado nombre del archivo src/Components/Home/Index.js a src/Components/Home/index.js, con minuscula.
Llamado al componente Home, src/Components/Home (sin index.js)

OT-130-ISSUE-#129-Cannot-find-file-index.js-in-src-Components-Home-Index.js

---

src/Components/Footer/Footer.js

Cambiado ``const  {organization} `` por `` const organization ``

correcion de variable organization en footer de layout principal

---

src/Campaigns/School/Content.js
src/Campaigns/Toys/Content/Content.js
src/Components/Countdown/Countdown.js
src/Helpers/daysUntilDate.js
src/routes/Public.js

- Creado componente de countdown dinámico para el contenido de campañas. 
- Agregado el componente con la fecha a las 2 campañas.

Feature/countdown dinámico

---

src/Components/Activities/index.js
src/Components/Auth/LoginForm.js
src/Components/Auth/ProtectedRoute.js
src/Components/Auth/RegisterForm.js
src/Screens/Activities/ActivitiesEdition.js

- En /activities había un footer extra. Lo saqué
- El login form validaba la contraseña innecesariamente. Lo saqué. 
- Agregada lógica para que un usuario especifico sea de adminsitador. 
- No se estaba obteniendo bien la data de isAuth o isAdmin en la protección de rutas.
- Agregado para que se inicie la sesión con el usuario recién registrado
- Solucionado errores del formulario de registro. Api devolvía 422 por no enviar 'name'.
- Los params de EditActivities usaban la manera vieja de obtener parámetros, empezó a fallar. Reemplazé por el hook useParams

Agregado un hardcodeo para hacer usuario admin. Y cosas que fui encontrando

---

src/Components/Home/Index.js

Se había agregado un header al layout de Home

Fix Header duplicado en landing

---

src/App.js
src/Campaigns/School/SchoolCampaign.js
src/Campaigns/Shared/FooterCampaings.js
src/Campaigns/Shared/HeaderCampaigns.js
src/Campaigns/Toys/ToysCampaign.js
src/Campaigns/index.js
src/Components/Contact/index.js
src/Components/Footer/Footer.js
src/Components/Home/Index.js
src/Components/Layout/Layout.js
src/Components/Members/MembersForm.js
src/Components/Testimonials/TestimonialsForm.js
src/Helpers/daysUntilDate.js
src/routes/CampaignsRoutes.js
src/routes/Public.js
src/routes/config.js

Se actualizo la reenderizacion de los footers. Con un renderizado condicional.

Ot 130 issue #136 renderización erronea de footers en pages contacto y campañas

---

src/Backoffice/Header.js
src/Backoffice/dashboard/CardsBackoffice.js
src/Backoffice/dashboard/ScreenDashboard.js
src/Components/Header/Header.js
src/Screens/Organization/Organization.js
src/routes/BackofficeRoutes.js

Solucionado problema de data en Organizacion backoffice.
Restauracion de backoffice y adicion de botones para el manejo en backoffice

Error al renderizar data en BackOffice de Organización #145

---

src/Components/Footer/Footer.js

Se agrego un condicional para renderizar si existe la información en el reducer.
.

Bug fix Footer

---

src/Components/Users/CreateEditUser.js
src/Components/Users/UserList.js
src/Components/Users/UsersForm.js
src/Helpers/messagesText.js
src/Services/usersService.js

Delete user no funcionaba. 
El formulario está mejorado pero hay unerror de la api al hacer request de Put

Fix / Delete user + Mejorado formulario en edit

---

src/Components/Auth/LoginForm.js

Hardcoded admin user

---

src/Screens/Organization/Organization.js

Agregado componente que estaba en /Activities, para insertar el html de ckeditor en texto y que no se muestren los p tags
fix #146

fix/ Organizations backoffice: Utilizado componente para insertar html

---

src/Campaigns/Toys/Content/Content.css
src/Campaigns/Toys/Content/Content.js
src/Components/Footer/Footer.js

Se modificó el css de él componente y re elimino la importación a una función que quedo obsoleta en un issue anterior,
#159

Ot130 client 159 error en campaña juguetes con la imagenes

---

src/Campaigns/School/SchoolCampaign.js
src/Campaigns/Toys/ToysCampaign.js
src/Components/Carousel/Carousel.js

Arreglados carousels de campañas

---

src/App.css
src/Components/Carousel/Carousel.css
src/Components/Home/CarouselHero.js
src/Components/Home/Hero.css
src/Services/mocks/schoolSliders.json

Texto de bienvenida del Home #144 
Imagenes en el slide de escuela

0 t130 issue#144 texto de bienvenida de la web publica y Imagenes en el slide de escuela.

---

src/Components/Activities/ActivitiesList.js
src/Components/Activities/ActivityItem.js
src/Components/Activities/ActivitySearchForm.css
src/Components/Activities/ActivitySearchForm.js
src/Components/Activities/BackofficeActivitiesList.js
src/Screens/Activities/ActivitiesEdition.js

Se agregó el buscador de actividades para el back y la web pública.
Se valida si esta logeado y si es administrador para que no se pueda editar en caso de que sea un usuario normal.
Se agrega botón para volver atrás al backoffice.

adding search form activities
